apiVersion: apps/v1
kind: Deployment
metadata:
  name: multithread-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multithread-react
  template:
    metadata:
      labels:
        app: multithread-react
    spec:
      containers:
        - name: multithread-container
          image: keyssong/react-multithread:latest
          imagePullPolicy: Always              
          ports:
            - containerPort: 5173                